### ISSUE TITLE
Android while running app after adding dependency FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ketankonrad** [MirrorFly/MirrorFly-Flutter-plugin#4]
**flutter doctor output**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4780], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.   
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**pubspec.yaml**

dependencies:
    mirrorfly_uikit_plugin: ^2.0.0

**DEBUG CONSOLE**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.michaelrocks:libphonenumber-android:8.9.14.
     Required by:
         project :app > project :mirrorfly_plugin > com.mirrorfly.sdk:mirrorflysdk:7.13.5
      > Could not resolve io.michaelrocks:libphonenumber-android:8.9.14.
         > Could not get resource 'https://repo.mirrorfly.com/release/io/michaelrocks/libphonenumber-android/8.9.14/libphonenumber-android-8.9.14.pom'.
            > Could not GET 'https://repo.mirrorfly.com/release/io/michaelrocks/libphonenumber-android/8.9.14/libphonenumber-android-8.9.14.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.hypertrack:hyperlog:0.0.10.
     Required by:
         project :app > project :mirrorfly_plugin > com.mirrorfly.sdk:mirrorflysdk:7.13.5
      > Could not resolve com.hypertrack:hyperlog:0.0.10.
         > Could not get resource 'https://repo.mirrorfly.com/release/com/hypertrack/hyperlog/0.0.10/hyperlog-0.0.10.pom'.
            > Could not GET 'https://repo.mirrorfly.com/release/com/hypertrack/hyperlog/0.0.10/hyperlog-0.0.10.pom'. Received status code 403 from server: Forbidden

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s
[!] Gradle threw an error while downloading artifacts from the network.
Retrying Gradle Build: #1, wait time: 100ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.michaelrocks:libphonenumber-android:8.9.14.
     Required by:
         project :app > project :mirrorfly_plugin > com.mirrorfly.sdk:mirrorflysdk:7.13.5
      > Could not resolve io.michaelrocks:libphonenumber-android:8.9.14.
         > Could not get resource 'https://repo.mirrorfly.com/release/io/michaelrocks/libphonenumber-android/8.9.14/libphonenumber-android-8.9.14.pom'.
            > Could not GET 'https://repo.mirrorfly.com/release/io/michaelrocks/libphonenumber-android/8.9.14/libphonenumber-android-8.9.14.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.hypertrack:hyperlog:0.0.10.
     Required by:
         project :app > project :mirrorfly_plugin > com.mirrorfly.sdk:mirrorflysdk:7.13.5
      > Could not resolve com.hypertrack:hyperlog:0.0.10.
         > Could not get resource 'https://repo.mirrorfly.com/release/com/hypertrack/hyperlog/0.0.10/hyperlog-0.0.10.pom'.
            > Could not GET 'https://repo.mirrorfly.com/release/com/hypertrack/hyperlog/0.0.10/hyperlog-0.0.10.pom'. Received status code 403 from server: Forbidden

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 47s
[!] Gradle threw an error while downloading artifacts from the network.
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by manivendhan-contus** [comment]
Upgrade to the latest beta release 

https://pub.dev/packages/mirrorfly_uikit_plugin/versions/2.0.1-beta

dependencies:
mirrorfly_uikit_plugin: ^2.0.1-beta

The above release is will resolve this issue. Stable version will be released soon.
